analyzer:
  errors:
    avoid_print: ignore
    constant_identifier_names: ignore
    deprecated_member_use: ignore
    library_private_types_in_public_api: ignore
    non_constant_identifier_names: ignore
    unnecessary_string_interpolations: ignore
    use_key_in_widget_constructors: ignore
include: package:flutter_lints/flutter.yaml
