name: weather
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: 
  get:
  geolocator:
  geocoding:
  intl:
  cupertino_icons:
  flutter_spinkit:
  url_launcher: 
  font_awesome_flutter:
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
   - assets/images/
